name: Release Version

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - run: npm install
    - run: npm run build 
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/particle-processing-rk.js"
